site_name: A tiny jurney into the Computer Vision 
theme:
  name: material

site_author: Marco Salvalaggio
site_description: >-
  DESCRIPTION

# Repository
repo_name: computer-vision-blog
repo_url: https://github.com/marcosalvalaggio/computer-vision-blog

# Configuration
theme:
  name: material
  features:
    - navigation.sections
    - navigation.top
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: indigo
      accent: deep purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: indigo
      accent: deep purple


extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/marcosalvalaggio
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/marco-salvalaggio-326795226/
  


markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  
plugins:
  - search